---
- name: Add EPEL repo
  yum:
    name: epel-release
    state: present
  become: yes

- name: Install a pip for Python2
  yum:
    name: python-pip
    state: present
  become: yes

- name: Install a Python3
  yum:
    name: python3
    state: present
  become: yes
