global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["172.17.0.1:9100"]
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "vps790031.ovh.net"

remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: #{prometheus_username}#
      password: #{prometheus_key}#
